version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Poc-SNS-SQS-Deploy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r1jxkz8k6jf9"
s3_prefix = "Poc-SNS-SQS-Deploy"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "TopicName=\"poc-sns-sqs-topic\" SqsName=\"poc-sns-sqs-queue\""
