AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Suffix:
    Type: String
    Default: .s3.us-east-2.amazonaws.com

Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CDN for S3-backed website
        Enabled: 'true'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: only-origin
          ViewerProtocolPolicy: allow-all
          CachePolicyId: !Ref CDNCache
        DefaultRootObject: index.html
        Origins:
        - CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
          DomainName: !Join ['', [!Ref 'S3BucketForWebsiteContent', !Ref Suffix]]
          Id: only-origin

  CDNCache:
    Type: AWS::CloudFront::CachePolicy
    Properties: 
      CachePolicyConfig: 
        Comment: My cutom policy
        DefaultTTL: 2592000
        MaxTTL: 31536000
        MinTTL: 86400
        Name: MyCustomCacheConfig
        ParametersInCacheKeyAndForwardedToOrigin: 
          CookiesConfig: 
            CookieBehavior: all
          EnableAcceptEncodingGzip: false
          HeadersConfig: 
            HeaderBehavior: none
          QueryStringsConfig: 
            QueryStringBehavior: all

Outputs:
  BucketName:
    Value: !Ref 'S3BucketForWebsiteContent'
    Description: Name of S3 bucket to hold website content
  CDNUrl:
    Value: !GetAtt 'WebsiteCDN.DomainName'
    Description: CDN url