version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Poc-APIGateway-Lambda-Deploy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r1jxkz8k6jf9"
s3_prefix = "Poc-APIGateway-Lambda-Deploy"
region = "us-east-2"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Stage=\"poc\" APIGatewayName=\"PocAPIGateway\" LambdaName=\"poc-lambda\""
image_repositories = []
